modLoader="javafml"
loaderVersion="[38,)"
license="GNU LGPLv3"
[[mods]]
modId="chickensshed"
version="${file.jarVersion}"
displayName="ChickensShed"
authors="holmraven"
description="Chickens shed their feathers occasionally."
[[dependencies.chickensshed]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
